sudo: false
language: android
jdk: oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-google-m2repository
  - extra-android-m2repository
env:
  global:
  - ANDROID_PLAY_JSON_FILE="../creds/google-play.json"
  - ANDROID_RELEASE_STORE_FILE="../creds/platypus-android.jks"
  - secure: --
  - secure: --
  - secure: --
  - secure: --
before_install:
- openssl aes-256-cbc -K $encrypted_3a18627f5297_key -iv $encrypted_3a18627f5297_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
script: "./gradlew build check"
deploy:
- provider: releases
  api_key:
    secure: --
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    repo: platypusllc/tablet
    tags: true
- provider: script
  script: "./gradlew publishApkRelease"
  skip_cleanup: true
  on:
    repo: platypusllc/tablet
    tags: true
