sudo: false
language: android
jdk: oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-google-m2repository
  - extra-android-m2repository
env:
  global:
  - ANDROID_PLAY_JSON_FILE="../creds/google-play.json"
  - ANDROID_RELEASE_STORE_FILE="../creds/platypus-android.jks"
  # ANDROID_RELEASE_STORE_PASSWORD
  - secure: h3k7NcAiSUdAT74594n+9+90s0263zQD6LfTkNL43BN1msCa1p9XylbsEF5r0NInWKAxy6ktD3ev0UbcnHVs5xwvmLGoFpAMDDV5iJ7WdGKYpHf0g8mBW3nYfwavqLNTgtVyZd3HtG+3q2lBAhm53slFgD3G7MhuQJp5fMIICd7mmHp6R6RKPskiHQNyhf9iAPk00qIU5HTKnJ7eHROFma6tRTTG5SsrsZvd6Bh/GmoeXl1qHnhR9NDqNzoWKd3azgG+/pEuZBqEZunubd2bvdjbcRrKgrSZknlkuYKOcQ1wH3n9fUgzttM1xf87GUTBf26ttv//+QzWjwWbHXVdtbvDDKsMIxVYekq3Sn4ZwIMD4mgpCsLnCb8KXCFxatpKnZWV1z8VxDF9G+gvQ8GqxUlyFxKU94RDCvKAZFdQhBinI3tZ/w2iTyOdRp91ZhHDHwIX/y1B7DK2GH7QRaCcnN3tHVvP7oO9k1koAjhoKQyRxSj6ISkuGWB43toFMbuDKsJvZWkxVzzaV/bCQzu1fpBkuWHlZb4gefaU5FqZlnLL2RCpvYXbY8zuoQ9C79CawApKRFR4Z/fPmqqJefBufs9xq++JJbfF5WYPLB7AA1STGn0RXZFk1EKxU8aP8idjn2slqhMuM5xSU97qXiaccVfitBbVVzEtseSKRxoXKfw=
  # ANDROID_RELEASE_KEY_ALIAS
  - secure: KjJ13kwzBCVc06dkWAjNJGVisERwLFLFaZUvLsa1g4SqnBegt66FseKix0KHg6MwQGFmnY7O1XKN75MYayQoQu9nH7POT7AKHIB/kvGniHc8tBaUvg/v4rMQ1z3m75Bj7t2CK8C3QiJW2vRfQOmIUGSL1/p7fOduMKRC9SbKuckrGaf62nw1yet/tVmQHwWWaVzINZY1CipfONSxhYI/hiec7Zt/Yd+uGanP4V1koPlYXj4XiBwo5EkMz4yG5mM/1j0sJrgO2jR6nxS5JAO3Z8BXwCXPefvU8lW6eYrcdfo6nR8ouP7G1U0Bv6DGJijPgXBkGszRKA5GyuIYKyS9sqaGQhx5vsCpy5QhQKnym90ZS1+AoQ0kchT49p34aEERZK4Ll/XhWF3CvYHtboEMA1MWzgXNOOw+IrlfkV0JZaBMF49WuXv5UDojp8dvydR1YjV44Qah7of1UOaHKdqMLVHfqWC18kth2jZfwRACNSYZcbqzzK90aGbUs04Gv5dcaZLRLvOeSiAc4UKjWYNdB1WQemob3xQk3tUwwf9x4tRZI4undexzuzxOvB/85/yEteIlbE1EsxzLCtBp+59to40xcVoQ4ejY72Fl99q1gaIxVowUtsKWLi4MH/F2uh/2xdYdbuq8HmA6DLtvTa8RkU/EV59jZWvUZoQL+pISxjU=
  # ANDROID_RELEASE_KEY_PASSWORD
  - secure: Z2IV/7zuu/DGcN+K32BD73cM4HIVJX0W6c3SRIEbLWRyVM/xulIAncPM4LZzlCN1tbs8jNTfd2eqS89LjTX6IO509BrpF0oBf76P4x3RM9kFuDMPVgejnj23i1pN7H8TipHEIidZn3V8hqc9LgwMM/SWGD+UaZRoeab75mGBH9MNrNzaeGikhHu/wVdjJuzJiGg//Ra52ITqtLvRoeWVvrI8T2hS1ioIDZtm0npp5fpe1mvfcAcZKGhqfQxFf+nKnEiRQXlu7RelKs86WFPlr9XobQkFf24IWg8DP3YFz4pyIEDRboG7wcvu2go1aeqF3ZD9PuIaBPWD6ff+YOtCPXU6Gijh2TaiodQkWQ9DV76TwBpqhiNU+MwzaJX+aIvxaCidRNtgxO/Koz4S6uFKLIMIbJSbt9Org2ED2ZVzv47lJlhRgbJbu//SFPNAFagZBmft6vVY0Vg2ao1avffNcTcgkoBWunh4W/RtCA5KC76ktrigqSxM4BtNqd6rB1MOgT59uLINUMbgDobmPzih2rQ/9bSsvnyZLhcAUbLI7O+rf0n7ictl5/UJHgWVgSdw3Kjic+nuRhuG1lKFLAj/S+3pybdxfC3tchHD3ThwubN2pA9PhP/6dV2onIs4K9U4+zjpGDDZtROMhT3kCZaHCP8X789lUELyqETjC9oTpu8=
  # MAPBOX_ACCESS_TOKEN
  - secure: WGeOULBCPGsj6blUyxfxtTtlXVK9Lki+lmJJNEg56JYbP9eVCdGsQeQjtEZYg3gCwOZAQNqofCQSw2qAyLo50YZAYXxSTUXltoHMb9+9ymhyoFpWxdMEBn1tz3RPq1A6eT/RlNV5B9MOdAoGzetaK1u8018gvvF1nye6uUsSRlMuP6Y9gtTXhh8HTnKVQeYaAVoUptX4bdKteX+JqMzO2gIAMD1WI8mhdrhoYBOqrIQkEbCji9mjnzGsrO5xHQ6EmsARoEY45Tf4E9oAy7FPPHRHIqGfURvOJBuemoRp9KORJp9b4KEJE+MgCEP3KDF1jTzq355+PzWL4TZRt3vUgoFgcuoaQVDo65IU1gnmobK37QpV9adbgLwclI0zFGxuuEAPZ4qFk7yp3qS50WLDvPCyDTduqzb1sU5XSQKZzm3j0fI9wnwXLRiOk1ZwFDCUP8K6BAs1YV6RR702CQmJc/PxoeUNPpifERlapzyfZeTWsYi1my/FIuuYMw0bdo0Pe0J/c6I6fY2R90sg4rKW7Gm8gx+NR3IQ3HwdDnZkiNL1HaUdbwU6rJ4o2GpnZjbilAqQeySBZ/98ieNskRQmJgKhuHT3IZsQlLvdkG/LXhc7fNM/5y7dXc5GL52Lh67D/ujCuli/11pd4jY3/fg+DCJCSjoLLoJ29Tc0Vv/AdxQ=
before_install:
- openssl aes-256-cbc -K $encrypted_abffbe2e7324_key -iv $encrypted_abffbe2e7324_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
script: "./gradlew build check"
deploy:
- provider: releases
  api_key:
    secure: sLVXroXsRF9lreKp0Ncke3b694iHj8rKaEUSVBMQ80XF15iHAo9nuTXFwjRMoY9AAPcm427GZ/2H2Y7vL0QzZjzDNFl1W8Yl7zldUeKtxdU7V6TUWoiSOntrNhuxTF0HNPjY2uewfLNbvZ5YIVPBjngzS0OlUKfp+4cIK7Fbh83XFilZReEBior8l3yx1x6LaG90TpczxJmXzUczlyqIdMixq3WqoC5eYslqYHkV86aYgtomr/iPYCOcCRoAdG9CupY6dlznWfxr8q5B+blA4C+W8Ad+mCtOC/EzQ2/7gSIIUMzcJlPtaENBAqZw6lC83hN52MOyy2dB2Dzgp5Cgd6uOdfWI/oK/vAl9Q/645jWA2Fmv5s7MfyN9Q+q+8KEql5jKHliM8pM9QJfxeC+cCRMk+v0hLnMSIcq2hLpDy1RXEoqmZIy5XC6BpSvqtqh8fW97CFZ+Eu9r6QG0FkLC62SZdLmxW0pmrtxi5RC+Czgf3NgKGxkxGi6zy/lW70bpQFgZIQJTjH1Hz5Hqvl4U+j7v8GQCEZOM//x7/gKd088JIsdTs9dQCer8V594096gatxo+gZWsanrfO693pkKGOVl4jZOoOcNDViCw/KJTt7dkGXIXjwsD1S5+tNw7MrRWD+8sGnfRwqfmd5eT3IoZqAuDsxUyoj8VHijEAUaPMY=
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    repo: platypusllc/tablet
    tags: true
- provider: script
  script: "./gradlew publishApkRelease"
  skip_cleanup: true
  on:
    repo: platypusllc/tablet
    tags: true
